#!/bin/sh

# Modbus functions aliases
CMD_READ_COILS=0x01
CMD_READ_DISCRETE_INPUTS=0x02
CMD_READ_HOLDING_REGISTERS=0x03
CMD_READ_INPUT_REGISTERS=0x04
CMD_WRITE_SINGLE_COIL=0x05
CMD_WRITE_SINGLE_REGISTER=0x06
CMD_WRITE_MULTIPLE_COILS=0x0F
CMD_WRITE_MULTIPLE_REGISTER=0x10

